version: '3.8'
services:
  client:
    container_name: gamehub-client-container
    build: .
    restart: always
    ports:
      - 3002:3002
    environment:
      STAGE: 'dev'
      NODE_ENV: 'development'
      PORT: '3002'
    