version: '3.8'
services:
  client:
    container_name: gamehub-client-container
    build: .
    # x-develop:
    #   watch:
    #     - action: sync
    #       path: ./
    #       target: /
    #     - action: rebuild
    #       path: package.json
    restart: always
    ports:
      - 6500:6500
    environment:
      STAGE: 'dev'
      NODE_ENV: 'development'
      PORT: '6500'
    